### ISSUE TITLE
Request new feature

### ISSUE THREAD

**Issue by tahtskiebasement** [kernelENREK/Z80_NavigationBar#1]
god day mate, request for a new feature where you can set the location of the bar whether top or bottom just like the new Windows Defender or the Skype Preview navigation bar. TY

**Comment by kernelENREK** [comment]
hey buddy. Maybe something like that?

![image](https://cloud.githubusercontent.com/assets/4211853/26025182/0593fdac-37e2-11e7-92f6-0c1ef4494229.png)

(Side note: This screen shot was edited from Paint.NET, not real feature)

I'm looking into Windows Defender (from W10 Creatros Update) and don't see how to set up "_left Navigation bar_" to top or bottom. I'm missing something? A Screen Shot would be nice :)

**Comment by tahtskiebasement** [comment]
something like this mate, the items can be set top then other in bottom, that would be a great enhancement on the control

![untitled](https://cloud.githubusercontent.com/assets/5902277/26134845/212b4d68-3ae4-11e7-8eda-723013c19880.png)

**Comment by kernelENREK** [comment]
Ok, i see now.

You could use two Navigation controls and perform some _Anchor hack_ to make this layout.

The _problem_ is that the Navigation control can grow if it has child nodes (like Demo#2 and Demo#3).

If you have a layout like Demo#1, placing two controls and default panel control with same backcolor as Navigation control, you could have someting like:

![image](https://cloud.githubusercontent.com/assets/4211853/26170779/defc4f46-3b42-11e7-9801-9165d1ea6982.png)

Note the Anchors of each control & panel 

Not the feature you request but hey, you know 😃

**Comment by tahtskiebasement** [comment]
oww, i did not think of that, I'm only using the demo 1, thanks for your hack, but it owuld be a great feature if implemented.
