### ISSUE TITLE
reduce blinking

### ISSUE THREAD

**Issue by tahtskiebasement** [kernelENREK/Z80_NavigationBar#5]
good day mate,

I am wondering how to reduce the blinking when transferring to another item.

**Comment by kernelENREK** [comment]
Hey dude, 

What do you mean when you say "transferring to another item"?

**Comment by tahtskiebasement** [comment]
when you switch to another navbaritem, the whole control flickers.

**Comment by kernelENREK** [comment]
Ok, i see!

i'm gonna Make a pull request with this fixed:

`Z80_Navigation.New() ---> Put inside: Me.DoubleBuffered = True`

`NavBarItemPanel.Initialize() ---> Put inside: Me.DoubleBuffered = True`

This should reduce the blinking

**Comment by kernelENREK** [comment]
Fixed (i hope) on commit https://github.com/kernelENREK/Z80_NavigationBar/commit/82c469099fbb429318f1cb16d2a89d3bb7951b7e
